# Postgres datasource (persistent)
spring.datasource.url=jdbc:postgresql://localhost:5432/desktrade
spring.datasource.username=postgres
spring.datasource.password=password
spring.jpa.hibernate.ddl-auto=update

# JWT
app.jwt.secret=luh+iSaRDKlezXEIhciCnBcG1KLY0oFGmQatqOxoeQg=
app.jwt.expiration-ms=21600000


# show SQL statements
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# show parameter values (bind)
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

